name: Dev Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

env:
  draft: true

jobs:
  dev-release:
    permissions: write-all
    name: Dev Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.8.0'

      - name: Get package version
        id: package-version
        run: echo "PACKAGE_VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV
        
      - name: Install dependencies
        run: npm install
      
      - name: Build files
        run: npm run build

      - name: Build tarballs
        run: npm run pack

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.PACKAGE_VERSION }}-${{ github.sha }}"
          name: "Release v${{ env.PACKAGE_VERSION }}-${{ github.sha }}"
          draft: ${{ env.draft }}
          prerelease: true
          files: ./dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token for GitHub API
