name: Dev Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  dev-release:
    permissions: write-all
    name: Dev Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.8.0'

      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        
      - name: Install dependencies
        run: npm install
      
      - name: Build files
        run: npm run build

      - name: Build tarballs
        run: npm run pack

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          files: ./dist/*.tar.gz
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
